client_config_backend: settings
client_config:
  client_id: put your client id from https://console.cloud.google.com/apis/credentials?project=bookstore-356512 here# you replace bookstore-356512 with your project name
  client_secret: put your client_secret  https://console.cloud.google.com/apis/credentials?project=bookstore-356512 # you replace bookstore-356512 with your project name

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install